services:
  db:
    image: postgres:17
    container_name: mindquest-db
    restart: always
    environment:
      POSTGRES_USER: mindquest
      POSTGRES_PASSWORD: mindquest
      POSTGRES_DB: mindquest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
